# Generated by Django 5.2.1 on 2025-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
